In [1]:
import  numpy as np
A=np.array([[1,2,3,4,5],
           [6,7,8,9,10],
           [11,12,13,14,15]])
print("Original Matrix:\n",A)

Original Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [2]:
sliced=A[0:2,1:3]
print("\nSliced Matrix:\n",sliced)


Sliced Matrix:
 [[2 3]
 [7 8]]


In [3]:
V=np.array([1,2,3,4,5])
broadcasted=A+V
print("\nBroadcasted Matrix:\n",broadcasted)


Broadcasted Matrix:
 [[ 2  4  6  8 10]
 [ 7  9 11 13 15]
 [12 14 16 18 20]]


In [4]:
bool_idx=A>6
print("\nBoolean Mask(A>6):\n",bool_idx)
print("Elements>6:\n",A[bool_idx])


Boolean Mask(A>6):
 [[False False False False False]
 [False  True  True  True  True]
 [ True  True  True  True  True]]
Elements>6:
 [ 7  8  9 10 11 12 13 14 15]


In [5]:
squared=A**2
print("\nSquared Matrix:\n",squared)


Squared Matrix:
 [[  1   4   9  16  25]
 [ 36  49  64  81 100]
 [121 144 169 196 225]]


In [6]:
B=np.array([[1,2,3,4],
            [3,4,5,6],
            [5,6,7,8],
            [7,8,9,10],
            [4,5,6,8]])
matmul=A@B
print("\nMatrix multiplication:\n",matmul)


Matrix multiplication:
 [[ 70  85 100 120]
 [170 210 250 300]
 [270 335 400 480]]
